### ISSUE TITLE
Feature: fuzzy patch maching

### ISSUE THREAD

**Issue by hazcod** [juju/httpgovernor#2]
Thank you for the package!
I think it would be nice to for example define:
- `/assets/` has a cost of 1
- `/api/` has a cost of 2
- `/api/heavy-call` has a cost of 3

**Comment by mhilton** [comment]
@hazcod thanks for the suggestion, I assume you are thinking of a `CostEstimator` which uses a similar matching algorithm to the one used in [http.ServeMux](https://golang.org/pkg/net/http/#ServeMux).

**Comment by mhilton** [comment]
This was added by #3
